- name: Use Image Builder
        run: |
          # 1. Download official Image Builder for 23.05.5
          wget https://downloads.openwrt.org/releases/23.05.5/targets/ipq40xx/generic/openwrt-imagebuilder-23.05.5-ipq40xx-generic.Linux-x86_64.tar.xz
          tar -J -xvf *.tar.xz
          cd openwrt-imagebuilder-23.05.5-ipq40xx-generic.Linux-x86_64
          
          # 2. Inject custom repos
          echo "src/gz eko1 https://dl.eko.one.pl/openwrt-23.05/packages/arm_cortex-a7_neon-vfpv4/eko1" >> repositories.conf
          echo "src/gz IceG_repo https://github.com/4IceG/Modem-extras/raw/main/myrepo" >> repositories.conf
          echo "src/gz openwrt-tailscale https://gunanovo.github.io/openwrt-tailscale/arm_cortex-a7_neon-vfpv4" >> repositories.conf
          
          # 3. Build the image with BOTH the engine and the UI
          # Note: luci-app-tailscale is pulled from the gunanovo repo we added above
          make image PROFILE="zte_mf286d" \
          PACKAGES="tailscale kmod-tun ca-bundle luci-proto-qmi uqmi usb-modeswitch luci luci-app-tailscale sysinfo luci-app-ksmbd" \
          IGNORE_SIGNATURE=1

          
      
